language: node_js
node_js:
- 6.11.1
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - wget "http://chromedriver.storage.googleapis.com/2.22/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - npm install -g webpack
  - npm install -g webpack-dev-server
  - npm install -g protractor
  - npm install
  - webdriver-manager update
  - npm start &
  - sleep 15
script:
 - npm test
notifications:
  email:
  - stollenwerk@kitconcept.com
